console.log("Hello I am om");
console.log("another one added");
console.log("Testing staging");
console.log("set up in p4");
console.log("commiting after cloning");
console.log("Login feature work");
console.log("Login feature completed");
console.log("Working on payment feature");
console.log("Still not finished");
console.log("Payment feature added");